//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMusteri
    {
        public int MusteriID { get; set; }
        public string AdiSoyadi { get; set; }
        public string Telefon { get; set; }
        public string TCNO { get; set; }
        public string telefon2 { get; set; }
    }
}
