//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOdalar
    {
        public int OdaID { get; set; }
        public string OdaAdi { get; set; }
        public Nullable<int> OdaNo { get; set; }
        public Nullable<bool> OdaDurumu { get; set; }
        public string Ozellik { get; set; }
        public Nullable<decimal> Ucret { get; set; }
    }
}
